<?php /* @var $this Mage_Core_Block_Template */ ?>
<?php if (Mage::getStoreConfigFlag('logger/sentry/adminhtml_enabled') && Mage::getStoreConfig('logger/sentry/public_dsn')): ?>
<script
  src="https://browser.sentry-cdn.com/6.17.9/bundle.min.js"
  integrity="sha384-bg8ATkDzxNiciak2tVJV/r+DHguxvOKHQqRi2SKP2mc8IOZphuG/bYdsyBm+KQC3"
  crossorigin="anonymous"
></script>
<script type="text/javascript">
Sentry.init({
  dsn: <?= json_encode(Mage::getStoreConfig('logger/sentry/public_dsn')) ?>,
  debug: <?php if (Mage::getIsDeveloperMode()): ?>true<?php else: ?>false<?php endif; ?>,
  attachStacktrace: true,
  release: <?= json_encode(Mage::helper('core')->getAppRelease()) ?>,
  environment: <?= json_encode(trim(Mage::helper('firegento_logger')->getLoggerConfig('sentry/environment')) ?: NULL) ?>,
});
Sentry.configureScope(scope => {
    <?php if (Mage::getSingleton('admin/session')->isLoggedIn()): ?>
    scope.setUser({
      id: <?= intval(Mage::getSingleton('admin/session')->getUser()->getId()) ?>,
      username: <?= json_encode(Mage::getSingleton('admin/session')->getUser()->getUsername()) ?>,
    })
    <?php endif; ?>
    <?php if ($installCode = Mage::helper('mwe')->getInstallCode()): ?>
    scope.setTag('instance_uid', <?= json_encode($installCode) ?>);
    <?php endif; ?>
});
</script>
<?php endif ?>